# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Skybeam
tagline:          'A Poem Archive.'
description:      "This is Calvin's new poem site. Below is an index of every poem. <br> Or you can simply scroll. Poems are sorted from newest to oldest. Enjoy."
url:              https://cal1pers.github.io
baseurl:          /skybeam/

# Plugins
#plugins:
 # [
 #   jekyll-paginate
 # ]

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

#paginate:         5

# Custom vars
version:          '0.5 Beta PVT'

github:
  repo:           https://github.com/Cal1pers/skybeam
