# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Skybeam
tagline:          'A Poem Archive.'
description:      "CW - mentions of suicide and generally depressing thoughts. This is Calvin's new poem site. Enjoy.  "
url:              https://cal1pers.github.io
baseurl:          /skybeam/

# Plugins
plugins:
  [
    jekyll-paginate
  ]

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Cal1pers/skybeam
